/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PostRouteImport } from './routes/post'
import { Route as ClaimsClaimIdRouteImport } from './routes/claims/$claimId'
import { Route as ItemsIdRouteImport } from './routes/items/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsClaimIdRoute = ClaimsClaimIdRouteImport.update({
  id: '/claims/$claimId',
  path: '/claims/$claimId',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/post': typeof PostRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/items/$id': typeof ItemsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/post': typeof PostRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/items/$id': typeof ItemsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/post': typeof PostRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/items/$id': typeof ItemsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/post'
    | '/claims/$claimId'
    | '/items/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/post'
    | '/claims/$claimId'
    | '/items/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/post'
    | '/claims/$claimId'
    | '/items/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  DashboardRoute: typeof DashboardRoute
  PostRoute: typeof PostRoute
  ClaimsClaimIdRoute: typeof ClaimsClaimIdRoute
  ItemsIdRoute: typeof ItemsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/$claimId': {
      id: '/claims/$claimId'
      path: '/claims/$claimId'
      fullPath: '/claims/$claimId'
      preLoaderRoute: typeof ClaimsClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  DashboardRoute: DashboardRoute,
  PostRoute: PostRoute,
  ClaimsClaimIdRoute: ClaimsClaimIdRoute,
  ItemsIdRoute: ItemsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
